ASadStateMachine.start_link()
ASadStateMachine.GenServer.echo_call("hello mike")
ASadStateMachine.GenServer.crash_with_cast()
ASadStateMachine.GenServer.call_self()
ASadStateMachine.StateMachine.echo_call("hello joe")
ASadStateMachine.StateMachine.crash_with_match()
ASadStateMachine.StateMachine.crash_with_raise()
ASadStateMachine.StateMachine.call_self()
ASadStateMachine.StateMachine.echo_call("hello joe")
